version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  danbot:
    build: .
    depends_on:
      - redis
    env_file:
      - ./.env

volumes:
  redis-data:
    driver: local
